name: CI/CD

on:
  push:
    branches: [ "cicd_311545" ]

jobs:
  windows-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: "3.8"
    - uses: actions/checkout@v3
    - name: python unit tests
      run: python -m unittest discover

  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: "3.8"
    - uses: actions/checkout@v3
    - name: python unit tests
      run: python -m unittest discover
